app/src/login/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, HiddenField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField('Usuário', id='username-login', name='username-login', validators=[DataRequired()])
    password = PasswordField('Senha', id='senha-login', name='senha-login', validators=[DataRequired()])
    submit = SubmitField('Entrar')
    nextpage = HiddenField()

app/sales/routes.py
from flask import Blueprint, current_app, render_template, jsonify, flash, get_flashed_messages, redirect, url_for, session, request
from app.helpers import login_required, flash_messages
from app.models import db, User, Customer, Sale, Product, SaleProducts
from app.sales.forms import *

sales = Blueprint('sales', __name__)

@sales.route('/sistema/home/vendas', methods=['GET'])
@login_required
def render_page():
    new_sale = SaleForm()
    messages = get_flashed_messages()

    return render_template(
        'vendas.html',
        pagetitle = 'Vendas',
        new_sale = new_sale,
        session = session,
        messages = messages
    )

@sales.route('/api/sales/register-sale', methods=['POST'])
@login_required
def register_sale():
    form = SaleForm()

    if form.validate_on_submit():
        customer_id = form.customer_id.data
        user_id = form.salesman_id.data
        
        
        try:
            if not Customer.query.filter_by(id=customer_id).first():
                raise Exception('Cliente não encontrado no banco de dados.') 
            
            if not User.query.filter_by(id=user_id).first():
                raise Exception('Vendedor não encontrado no banco de dados.')
            
            sale = Sale(
                total = 0,
                discount = form.discount.data,
                salesman_id = form.salesman_id.data,
                customer_id = form.customer_id.data
            )
            db.session.add(sale)
            db.session.commit()

            total = 0
            for product_form in form.products.entries:
                product = Product.query.filter_by(id=product_form.data['id']).first()

                if not product:
                    raise Exception(f'Produto com ID {product_form.data['id']} não encontrado no banco de dados.')
                
                sale_product = SaleProducts(
                    sale_id = sale.id,
                    product_id = product.id,
                    quantity = product_form.data['quantity']
                ) 
                db.session.add(sale_product)
                total += float(product.price) * float(product_form.data['quantity'])
            
            sale.total = total - (total * (form.discount.data/100))
            db.session.commit()
            flash("Venda registrada com sucesso!")
        except Exception as e:
            db.session.rollback()
            flash(f'Erro ao registrar venda - {e}')
    else:
        flash(form.errors)
    return redirect(url_for('sales.render_page'))

app/src/home/routes.py
from flask import Blueprint, render_template, session
from app.helpers import login_required
from app.models import User, Customer, Product, SaleProducts, Sale, db
from sqlalchemy import text, func
from math import floor

home = Blueprint('home', __name__)

@home.route('/sistema/home', methods=['GET'])
@login_required
def render_page():
    '''
    Métodos:
    - GET: renderiza a página Home do sistema.

    Principais Argumentos Renderizados:
    - qt_sales (int): valor que define a quantidade de vendas registradas.
    - qt_customers (int): valor que define a quantidade de clientes registrados, não incluindo o 'Não Registrado'.
    - qt_users (int): valor que define a quantidade de colaboradores que utilizam o sistema, não incluindo o Usuário 'Master'.
    - qt_products (int): valor que define a quantidade de produtos em estoque.
    - qt_sale_products (int): valor que define a quantidade de produtos vendidos.
    - total (int): valor que define o valor total de dinheiro arrecadados por venda.
    '''
    user = User.query.filter_by(username=session['logged_user']).first()
    first_name = ''
    for ch in user.name:
        if ch == ' ':
            break
        first_name += ch

    total = db.session.execute(text('SELECT SUM(sales.total) FROM sales;')).first()
    products = db.session.execute(text('SELECT SUM(products.quantity) FROM products WHERE    products.status = 1;')).first()
    sale_products = db.session.execute(text('SELECT SUM(products.quantity) FROM sale_products products;')).first()
    customers = Customer.query.filter((Customer.status == 1) & (Customer.id > 0)).count()
    users = User.query.filter_by(status=1).count()
    sales = Sale.query.count()

    return render_template(
        'home.html',
        pagetitle='Home',
        name = first_name.title(),
        role = str(user.roles.desc).title(),  
        session = session,
        qt_sales = sales,
        qt_customers = customers,
        qt_users = users-1 if users else 0,
        qt_products = products[0] if products[0] is not None else 0,
        qt_sale_products = sale_products[0] if sale_products[0] is not None else 0  ,
        total = floor(total[0]) if total[0] is not None else 0
    )

app/src/login/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, get_flashed_messages, session, request
from app.helpers import login_required, flash_messages, bcrypt
from app.src.login.forms import LoginForm
from app.models import *

login = Blueprint('login', __name__)

@login.route('/', methods=['GET'])
def root():
    '''
    Endpoint root, que ao ser acessado por método GET, redireciona o usuário para a página de login ou para a home do sistema (caso o usuário não esteja logado).
    '''
    return redirect(url_for('login.render_page', next=url_for('home.render_page')))

@login.route('/sistema/login', methods=['GET'])
def render_page():
    '''
    Renderiza a página Web com o formulário de Login através do método GET.
    '''
    form = LoginForm()

    return render_template(
        'login.html', 
        next = url_for('home.render_page'), 
        form = form, 
        messages = get_flashed_messages()
    )

@login.route('/sistema/login/validate', methods=['POST'])
def validate_login():
    '''
    Valida as informações de tentativa de acesso na página de Login, por método POST.
    '''
    form = LoginForm()

    if form.validate_on_submit():
        next = str(form.nextpage.data)
        username = str(form.username.data)
        passwd = str(form.password.data)
        
        try:
            found_user = User.query.filter(User.username == username).first()
            
            if (not (found_user and bcrypt.check_password_hash(found_user.password, passwd) and found_user.status)):
                raise Exception('Usuário ou senha inválidos')
            
            role = UserRole.query.filter_by(id=found_user.role_id).first()
            session['logged_in'] = True
            session['logged_user'] = username
            session['user_role'] = role.desc
            return redirect(url_for('home.render_page'))
        except Exception as e:
            flash(f'Erro ao validar login - {e}')
    else:
        flash_messages(form.errors)
    return redirect(url_for('login.render_page', next=next))
        

@login.route('/sistema/logout', methods=['GET'])
@login_required
def logout():
    '''
    Finaliza a sessão do usuário logado no sistema.
    '''
    session.pop('logged_in')
    session.pop('logged_user')
    session.pop('user_role')
    return redirect(url_for('login.render_page', next=url_for('home.render_page')))

app/users/routes.py
from flask import Blueprint, render_template, jsonify, get_flashed_messages, flash, redirect, url_for, request, session
from app.models import db, User, UserRole
from app.users.forms import * 
from app.helpers import login_required, adm_required, flash_messages, bcrypt

users = Blueprint('users', __name__)

@users.route('/sistema/home/usuarios', methods=['GET'])
@login_required
@adm_required
def render_page():
    new_users = NewUserForm()
    change_passwd = ChangePasswdForm()
    edit_user = EditUserForm()
    delete_user = DeleteUserForm()
    users = User.query.all()
    messages = get_flashed_messages()
    
    return render_template(
        'usuarios.html', 
        pagetitle = 'Usuários',
        new_users = new_users,
        change_passwd = change_passwd,
        edit_user = edit_user,
        delete_user = delete_user,
        messages = messages,
        session = session,
        users = users
    )


@users.route('/api/users/<int:id>', methods=['GET'])
@login_required
@adm_required
def get_user(id: int):
    user = User.query.filter_by(id=id).first()

    return jsonify({
        'id' : user.id,
        'name' : str(user.name).title(),
        'username' : user.username,
        'role_id' : user.role_id,
        'email' : user.email,
    })


@users.route('/api/users/new', methods=['POST'])
@login_required
@adm_required
def new_user():
    form = NewUserForm()

    if form.validate_on_submit():
        name = str(form.name.data).strip().lower()
        username = str(form.username.data).strip()
        role_id = form.role_id.data
        passwd = str(form.password.data).strip()
        confirm_passwd = str(form.confirm_password.data).strip()
        email = str(form.email.data).strip()

        
        try:
            if User.query.filter_by(email=email).first():
                flash(f'Usuário já cadastrado com o email "{email}".')
            elif User.query.filter_by(username=username).first():
                flash(f'Já existe usuário cadastrado com o username "{username}"')
            elif passwd != confirm_passwd: 
                flash(f'Os campos de senha não são idênticos.')
            else:
                db.session.add(User(
                    name=name, 
                    username=username, 
                    email=email, 
                    role_id=role_id, 
                    password=bcrypt.generate_password_hash(passwd).decode('utf-8'))
                )
                db.session.commit()
                flash(f'Usuário "{username}" criado com sucesso!')
        except Exception as e:
            flash(f'Erro no cadastro de usuário - {e}')
    else:
        flash_messages(form.errors)
    return redirect(url_for('users.render_page'))
        

@users.route('/api/users/mudar-senha', methods=['POST'])
@login_required
@adm_required
def change_password():
    form = ChangePasswdForm()

    if form.validate_on_submit():
        id = form.id.data
        new_passwd = str(form.new_password.data).strip()
        confirm = str(form.confirm.data).strip()

        if new_passwd != confirm:
            flash('Os campos de senha devem ser idênticos.')
        elif len(new_passwd) < 10:
            flash('A senha deve possuir pelo menos 10 caracteres.')
        else:
            try:
                user = User.query.filter_by(id=id).first()
                if not user:
                    flash(f'Usuário com o id {user.username} não encontrado no banco de dados.')
                else:
                    user.password = bcrypt.generate_password_hash(new_passwd).decode('utf-8')
                    db.session.commit()
                    flash('Senha alterada com sucesso!')
            except Exception as e:
                flash(f'Erro ao realizar mudança de senha - {e}')
    else:
        flash_messages(form.errors)
    return redirect(url_for('users.render_page'))

@users.route('/api/users/editar', methods=['POST'])
@login_required
@adm_required
def edit_user():
    form = EditUserForm()

    if form.validate_on_submit():
        id = form.id.data
        name = str(form.name.data).strip()
        username = str(form.name.data).strip()
        role_id = form.role_id.data
        email = str(form.email.data).strip()

        try:
            user = User.query.filter_by(id=id).first()
            user.name = name
            user.username = username
            user.role_id = role_id
            user.email = email
            db.session.commit()
            flash(f'Usuário {username} alterado com sucesso!')
        except Exception as e:
            flash(f'Erro ao editar usuário - {e}')
    else:
        flash_messages(form.errors)
    return redirect(url_for('users.render_page'))

@users.route('/api/users/delete', methods=['POST'])
@login_required
@adm_required
def delete_user():
    form = DeleteUserForm()

    if form.validate_on_submit():
        id = form.id.data

        try:
            user = User.query.filter_by(id=id).first()
            username = user.username

            if not user:
                flash('Usuário ainda não cadastrado.')
            else:
                db.session.query(User).filter_by(id=id).delete()
                db.session.commit()
                flash(f'Usuário "{username}" removido com sucesso.')
        except Exception as e:
            db.session.rollback()
            flash(f'Erro ao deletar usuário - {e}')
    else:
        flash_messages(form.errors)
    return redirect(url_for('users.render_page'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/base.css')}}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='/images/favicon.png')}}" type="image/x-icon">
    {% block css_imports %}
    {% endblock %}
    <title>{{ pagetitle }}</title>
</head>
<body class="bg-body-tertiary">
    {% block modal %} {% endblock %}
    
    <main class="d-flex min-vh-100">
        <section id="side-nav" class="collapse-horizontal in show bg-dark text-light p-2">
            <ul class="text-center p-2">
                <!-- Divisoria 1 -->
                <li class="py-1"><a class="link-light link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" href="{{ url_for('home.render_page') }}"><i class="bi bi-house p-1 d-xl-inline d-none"></i> Home</a></li>
                <li class="py-1"><a class="link-light link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" href="{{ url_for('inventory.render_page') }}"><i class="bi bi-box p-1 d-xl-inline d-none"></i> Estoque</a></li>
                <li class="py-1"><a class="link-light link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" href="{{ url_for('customers.render_page') }}"><i class="bi bi-people d-xl-inline d-none"></i> Clientes</a></li>
                <li class="py-1"><a class="link-light link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" href="{{ url_for('sales.render_page') }}"><i class="bi bi-journal-text d-xl-inline d-none"></i> Vendas</a></li>
            </ul>
            
            <hr>
            
            <ul class="p-3 text-center">
                <!-- Divisoria 2 -->
                {% if session['user_role'] in ['master', 'admin'] %}
                <li class="p-1"><a class="link-light link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" href="{{ url_for('users.render_page') }}"><i class="bi bi-person-badge d-sm-inline d-none"></i> Usuários</a></li>
                {% endif %}
                <li class="py-1"><a class="link-light link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" href="{{ url_for('login.logout') }}"><i class="bi bi-box-arrow-left"> Logout</i></a></li>
                <li><button type="button" class="btn btn-outline-light d-xl-none mt-5" data-bs-target="#side-nav" data-bs-toggle="collapse">
                    <i class="bi bi-x"></i>
                </button></li>
            </ul>
        </section>        
        
        <section class="content p-4 w-100 w-100 overflow-y-auto">
            <div class="sticky-bottom">
                <button class="btn btn-outline-dark float-end" data-bs-toggle="collapse" data-bs-target="#side-nav" type="button"><i class="bi bi-list"></i></button>
            </div>
            {% block content %} {% endblock %}
        </section>

        
        <section id="toasts-container" class="toast-container position-fixed bottom-0 end-0 p-3">
            {% if messages %}
            {% set counter = 0 %}
            {% for msg in messages %}
            <div id="liveToast-{{ counter }}" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <strong class="me-auto">Sistema</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    {{ msg }}
                </div>
            </div>
            {% set counter = counter + 1 %}
            {% endfor %}
            {% endif %}
        </section>
    </main>
    
    {% block js_imports %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>    
    {% if messages %}
    <script src="{{ url_for('static', filename='javascript/toasts.js')}}"></script>
    {% endif %} 
</body>
</html>

app/templates/compras.html
{% extends "base.html" %}

{% block content %}
<div class="dashboard-content">
    <h1>{{ pagetitle }}</h1>

    
</div>
{% endblock%}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css')}}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='/images/favicon.png')}}" type="image/x-icon">
    <title>Login</title>
</head>
<body>
    <main class="d-flex vh-100">
        <section class="d-flex align-items-center justify-content-center mx-auto w-75 bg-body-tertiary">
            <div class="container rounded-5 text-dark shadow-xl w-sm-50 p-4 bg-dark-subtle">
                <h2 class="text-center mb-4">Login</h2>
                <form method="POST" action="{{ url_for('login.validate_login') }}">
                    {{ form.csrf_token }}
                    {{ form.nextpage(value=next) }}
                    <div class="row md-2 w-40 mx-auto">
                        {{ form.username.label(class="form-label m-0") }} {{ form.username(size=15, class="form-control", placeholder="Seu nome de usuário") }}
                    </div>
                    <div class="row mt-2 mb-4 w-40 mx-auto">
                        {{ form.password.label(class="form-label m-0") }} {{ form.password(size=15, class="form-control", placeholder="Sua senha") }}
                    </div>
                    <div class="row m-2 justify-content-center text-center">
                        {{ form.submit(class="btn btn-primary rounded-pill w-25 p-auto") }}
                    </div>
                </form>
            </div>
        </section>

        <section class="d-none d-sm-flex align-items-center justify-content-center w-50 h-100 bg-dark">
            <div class="text-center text-light w-75">
                <h1>Sistema de Gerenciamento de Estoque</h1>
                <p>Desenvolvido por Vinícius Toshio A. Hayashida, 2025</p>
            </div>
        </section>
    </main>
    
    {% if messages %}
    <section id="toasts-container" class="toast-container position-fixed bottom-0 end-0 p-3">
        {% set counter = 0 %}
        {% for msg in messages %}
        <div id="liveToast-{{ counter }}" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <strong class="me-auto">Sistema</strong>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                {{ msg }}
            </div>
        </div>
        {% set counter = counter + 1 %}
        {% endfor %}
    </section>
    {% endif %}

    {% if messages %}
    <script src="{{ url_for('static', filename='./javascript/toasts.js')}}"></script>
    {% endif %} 
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>    
</body>
</html>

app/templates/nota_fiscal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{{ pagetitle }}</title>
</head>
<body>

    <h1>REGISTRO DE VENDA</h1>

    <h2>Informações Gerais</h2>
    <table class="table table-bordered">
        <tr>
            <th >ID da Compra</th>
            <td>{{ sale.id }}</td>
        </tr>
        <tr>
            <th>Data da Venda</th>
            <td>{{ sale.sell_date.strftime('%d/%m/%Y') }}</td>
        </tr>
        <tr>
            <th>Valor Total</th>
            <td>R${{ sale.total }}</td>
        </tr>
        {% if sale.discount %}
        <tr>
            <th>Desconto</th>
            <td>{{ sale.discount }}%</td>
        </tr>
        {% endif %}
    </table>

    
    <h2>Informações do Cliente</h2>
    <table class="table table-bordered">
        <tr>
            <th>ID do Cliente</th>
            <td>{{ customer.id }}</td>
        </tr>
        <tr>
            <th>Nome Completo</th>
            <td>{{ customer.name.title() }}</td>
        </tr>
        <tr>
            <th>CPF</th>
            <td>{{ customer.cpf }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ customer.email }}</td>
        </tr>
        <tr>
            <th>Endereço</th>
            <td>{{ customer.address.title() }}</td>
        </tr>
    </table>

    <h2>Informações do Vendedor</h2>
    <table class="table table-bordered">
        <tr>
            <th>ID do Vendedor</th>
            <td>{{ salesman.id }}</td>
        </tr>
        <tr>
            <th>Nome Completo</th>
            <td>{{ salesman.name.title() }}</td>
        </tr>
    </table>

    <!-- Products Purchased -->
    <h2 class="section-title">Produtos Comprados</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID do Produto</th>
                <th>Descrição</th>
                <th>Quantidade</th>
                <th>Preço por Unidade</th>
                <th>Preço Total</th>
            </tr>
        </thead>
        <tbody>
            <!-- Adição dinâmica de produtos -->
            {% for product in products %}
                <tr>
                    <td>{{ product['product_data'].id }}</td>
                    <td>{{ product['product_data'].desc.title() }}</td>
                    <td>{{ product['sale_quantity'] }}</td>
                    <td>R${{ product['product_data'].price }}</td>
                    <td>R${{ product['product_data'].price * product['sale_quantity']}}</td>
                </tr>
            {% endfor %}
            <tr>
                <th colspan="4" class="text-center">Subtotal</td>
                <td>R${{ subtotal }}</td>
            </tr>
            <tr>
                <th colspan="4" class="text-center">Desconto</td>
                <td>-R${{ discount }}</td>
            </tr>
            <tr>
                <th colspan="4" class="text-center">Total</td>
                <td>R${{ total }}</td>
            </tr>
        </tbody>
    </table>

</body>
</html>

app/templates/vendas.html
{% extends "base.html" %}

{% block modal %}
{% if users and products %}
<section id="modal-registrar-venda" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Registrar Venda</h5>
            </div>
            <form action="{{ url_for('sales.register_sale') }}" method="post">
                {{ new_sale.csrf_token }}
                <div class="modal-body">
                    <div class="row mb-2">
                        <div class="col">
                            {{ new_sale.customer_id.label(class="form-label") }} {{ new_sale.customer_id(class="form-control") }}
                        </div>
                        <div class="col">
                            {{ new_sale.discount.label(class="form-label") }} {{ new_sale.discount(class="form-select") }}
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col">
                            {{ new_sale.salesman_id.label(class="form-label") }} {{ new_sale.salesman_id(class="form-select") }}
                        </div>
                    </div>

                    <div class="d-block w-100 mb-2">
                        <label for="products" class="form-label">Produtos</label>
                        <div id="container-produtos">
                            <!-- Campos adicionados de forma dinâmica -->
                        </div>
                        <div class="w-100 text-center">
                            <button type="button" class="btn btn-outline-secondary" id="botao-adicionar-produto">Adicionar Produto</button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancelar</button>
                    {{ new_sale.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</section>
{% endif %}
{% endblock %}

{% block content %}

<h1>{{ pagetitle }}</h1>
<div id="container-todos">
    <input type="hidden" id="users" name="users" value="{{ users }}">
    <input type="hidden" id="products" name="products" value="{{ products }}">

    <div class="d-block w-100 mt-3">
        {% if users and products %}
        <!-- Fullscreen -->
        <div id="botoes-vendas" class="d-xl-inline d-none float-start">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-registrar-venda">Registrar Venda</button>
        </div>
        {% endif %}

        <!-- Mobile -->
        <div class="d-xl-none float-start">
            <div class="dropdown">
                <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-tools"></i></button>
                <ul class="dropdown-menu dropdown-menu-dark">
                    <li><button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#modal-registrar-venda">Registrar Venda</button></li>
                </ul>
            </div>
        </div>

        <div class="input-group mb-2 w-50 float-end">
            <input id="barra-pesquisa" type="text" class="form-control w-50" placeholder="ID, Cliente, Vendedor">
            <button id="botao-pesquisa" type="button" class="btn btn-outline-primary"><i class="bi bi-search"></i></button>
            <a href="{{ url_for('sales.render_page') }}" class="btn btn-outline-secondary d-none d-sm-inline"><i class="bi bi-arrow-clockwise"></i></a>
        </div>
    </div>

    <div id="tabela-vendas" class="d-flex table-responsive w-100 mt-5">
        <table class="table table-hover text-center">
            <thead class="table-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Vendedor</th>
                    <th scope="col">Data da Venda</th>
                    <th scope="col">Total</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody id="body-tabela-vendas">
                <!-- registro das vendas -->
            </tbody>
        </table>
    </div>
</div>

<div id="botoes-paginas" class="text-center m-2">
    <button id="botao-anterior" class="btn btn-secondary" type="button">Anterior</button>
    <button id="botao-proxima" class="btn btn-secondary" type="button">Proximo</button>
</div>
{% endblock%}

{% block js_imports %}
<script src="{{ url_for('static', filename='javascript/load_sales.js') }}"></script>
{% endblock %}